name: test

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches: [ "1.21.5-Fabric" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v5
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
       gradle-version: '8.14.2'

    - name: Build jar
      run: |
        chmod +x gradlew
        ./gradlew genSources
        ./gradlew build -Duser.timezone=Asia/Shanghai
